Create Release-note_20240709
e2info/cloudreport-docs pull request #101
Opened 2024-07-08 08:38 UTC by e2info-hashiguchi

・リリースノート（20240709）作成
・アーカイブに20240709追加、並び順を最新日順に変更
・最新リリース情報を20240709に変更

2024-07-09 00:33 UTC, e2kaneko requested changes
コメント確認お願いします

2024-07-09 00:33 UTC, e2kaneko commented on release-notes/index.md
> +* [2024/07/09【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりました](/cloudreport-docs/release-notes/20240709_00)
@e2info-hashiguchi 

①2024/07/09【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりましたの「【機能改修】」はいままでにないルールでしょうか？

②リリース後に、
2024/07/09【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりました
↓
【リリース完了】【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりました
になる想定ですか？

2024-07-09 01:07 UTC, e2info-hashiguchi commented on release-notes/index.md
> +* [2024/07/09【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりました](/cloudreport-docs/release-notes/20240709_00)
@e2kaneko
申し訳ないです。全体的にHR Deliでのリリースノートの書き方になっていてクラウドドキュメント用に調整しできていませんでした。
※HR Deliの書き方を変えている経緯
タイトルを見ただけでは何が更新されたか利用者が把握できない（ページ遷移して更新内容を見る必要があるため、結果的にそこまでして見ない可能性が高い）ので、クラウドログやSmartHRなどのサービスと同様にタイトル「【種別】更新内容」としていました。

①あってます（HR Deliに合わせた書き方）

②メンテナンス不要な機能の更新については、リリース後に更新する想定でした。そのため、「【リリース完了】」は入りません。
【例】不具合の修正やメンテナンスがある場合など事前に把握が必要な場合
（前）【不具合】○○について
（後）【対応済み】○○について

2024-07-09 01:16 UTC, e2info-hashiguchi commented on release-notes/20240709_00.md
> +2024年7月9日(火)に行ったリリースの詳細を報告いたします（機能改修1件）
@e2kaneko 
> 公開時点でコンタクト階層の参照が利用できるように見える？
「現時点の文面的に利用できるように見えるか」という意味でしたら利用できるよう見えます。ので、リリース前の文面を修正してマージするか、リリース後にマージしていただくことになります。

大変恐縮ですが、よろしくお願いいたします

2024-07-09 02:03 UTC, e2kaneko commented on release-notes/index.md
> +* [2024/07/09【機能改修】コンタクト(Contact)階層を参照している項目が出力可能となりました](/cloudreport-docs/release-notes/20240709_00)
@e2info-hashiguchi 了解しました。今後はデリに合わせる運用で問題ありません。よろしくお願いします。

2024-07-09 02:04 UTC, e2kaneko commented on release-notes/20240709_00.md
> +2024年7月9日(火)に行ったリリースの詳細を報告いたします（機能改修1件）
@e2info-hashiguchi リリース後にマージしますね

2024-07-18 01:43 UTC, e2kaneko approved these changes
確認しました

2024-07-18 01:43 UTC, merged